### ISSUE TITLE
Potential impact to LOTW performance

### ISSUE THREAD

**Issue by dkozinn** [klinquist/lotw-qsl-push-notification#1]
You might want to contact the ARRL, specifically W5OV who is their operations manager, and ask if this could be an issue if a bunch of people start running it.  There have been performance issues for LoTW lately that are caused by applications repeatedly polling. It seems this application would have the potential to do that as it will repeatedly cause the backend server to generate a report every 10 minutes. Even though you appear to be restricting by date range, that is still a non-trivial amount of work for the server. If one users does it I'm sure it's not a big deal, but imagine 100 or 1000 doing this over and over again.

**Comment by klinquist** [comment]
Thanks for the comment.  I'll reach out to them.

As an API developer myself, it seems silly that an _authenticated_ API wouldn't have reasonable hard rate limits - or even published Terms of Use with rate limit recommendations.

**Comment by dkozinn** [comment]
This has been a topic of discussion recently. The system itself is around 20 years old, and unfortunately hasn't had the resources to be significantly upgraded for quite some time. After some improvements were made a few years ago, users were encouraged to use it as often as they wanted, and because there were no rate limits, there have been a couple of recent incidents the really clobbered performance. I'm just an LoTW user so what I know is what I've seen on the various lists, but when this was developed nobody thought about rate-limiting. 

In any case, thanks for responding quickly, and I hope there is a mutually satisfactory resolution.

**Comment by klinquist** [comment]
Update, I just sent an email to W5OV.

**Comment by klinquist** [comment]
Bob is OK with the current approach of 2hr polling / 10 day past request.  He asked about the API response time, I said it was ~2seconds.

Quoting him:

> The shorter the time span you request data for results in higher prioritization in the “shared” download queueing.
> 
> What causes trouble is people requesting records from the beginning of time until now.  They immediately get lowest priority and minimal CPU usage.  Their queries could run for hours or longer.  The fact that nothing that occurred prior to 1945 is in the database escapes many of the programmers out there as they use “1900” as the start year.
